version: '3.4'

services:
    saveipapi:
        image: ${DOCKER_REGISTRY-}saveipapi
        build:
            context: src
            dockerfile: Dockerfile
        ports:
            - "8080"
            - "8081"
        volumes:
            - saveapidata:/data
    seq:
        image: datalust/seq:latest
        ports:
          - "5341:80"
        environment:
          ACCEPT_EULA: "Y"
        restart: unless-stopped
volumes:
    saveapidata: