version: '3.4'

services:
    saveipapi:
        image: ${DOCKER_REGISTRY-}saveipapi
        build:
            context: src
            dockerfile: Dockerfile
        ports:
            - "8080"
            - "8081"
        volumes:
            - saveapidata:/data
volumes:
    saveapidata: